config/routes.rb
Rails.application.routes.draw do
  root "gordens#index"

  resources "gordens", only: [:show] do
    member do
      get :gardener
    end

    resources "plants", only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/gorden.rb
class Gorden < ApplicationRecord
  has_many :plants
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :gorden

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gordens_controller.rb
class GordensController < ApplicationController
  def index
    @gordens = Gorden.all
  end

  def show
    @gorden = Gorden.find(params[:id])
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_gorden, only: [:new, :create]

  def new
    @plant = Plant.new
  end

  def create
    @plant = Plant.new(plant_params)
    @plant.gorden = @gorden
    if @plant.save
      redirect_to gorden_path(@gorden)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_gorden
    @gorden = Gorden.find(params[:gorden_id])
  end

  def plant_params
    params.require(:plant).permit(:name, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gordens_helper.rb
module GordensHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/gordens/index.html.erb
<div class="container">
  <h1>Gardens:</h1>
  <div class="gardens-container">
    <% @gordens.each do |garden| %>
      <a href="<%= gorden_path(garden) %>"
        class="garden-card"
        style="background-image: linear-gradient(rgba(0,0,0,.3), rgba(0,0,0,.3)), url('<%= garden.banner_url %>')">
        <h2><%= garden.name %></h2>
      </a>
    <% end %>
  </div>
</div>

app/views/gordens/show.html.erb
<div class="garden-banner" alt="garden banner"
     style="background-image: linear-gradient(rgba(0,0,0,.3), rgba(0,0,0,.3)), url('<%= @gorden.banner_url %>')">

  <h1><%= @gorden.name %></h1>
</div>


<div class="container">
  <%= link_to "➕", new_gorden_plant_path(@gorden) %>
  <div class="plant-container">

    <% @gorden.plants.each do |plant| %>
      <div class="garden-card"
            style="background-image: linear-gradient(rgba(0,0,0,.3), rgba(0,0,0,.3)), url('<%= plant.image_url %>')">
        <h2><%= plant.name %></h2>
      </div>
    <% end %>

  </div>
  <%= link_to "Back to gardens", root_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Garden</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plants/create.html.erb
<h1>Plants#create</h1>
<p>Find me in app/views/plants/create.html.erb</p>

app/views/plants/new.html.erb
<div class="container">
  <h1>Plants#new</h1>
  <p>Find me in app/views/plants/new.html.erb</p>

  <%= simple_form_for [@gorden, @plant] do |form| %>
    <%= form.input :name %>
    <%= form.input :image_url %>

    <%= form.submit %>
  <% end %>
</div>